/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/carreras": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar las carreras de la Facultad
     * @description El catálogo completo, ordenado por identificador.
     *
     *     **Devuelve una lista vacía si el corpus no está indexado, y no un error.**
     *     Es la misma decisión que toma el armado del servicio de recuperación: la
     *     aplicación tiene que levantar en una base recién migrada, y para quien
     *     consulta «todavía no hay corpus» y «no hay carreras de ese nivel» se
     *     contestan igual.
     *
     *     No pagina: son doce fragmentos y paginarlos sería inventar un problema.
     */
    get: operations["listar_carreras_api_carreras_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/carreras/buscar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar carreras por lo que la persona describe
     * @description Las carreras más cercanas a una descripción, de mayor a menor parecido.
     *
     *     Es la puerta para quien no sabe cómo se llama lo que busca. El `puntaje`
     *     ordena y **no es un porcentaje de acierto**: el índice devuelve
     *     `1 - distancia_coseno`, que puede ser negativo.
     *
     *     Va antes que `/{id_carrera}` en el archivo a propósito: FastAPI resuelve las
     *     rutas en orden, y declarada después, `buscar` la capturaría el parámetro de
     *     camino y se iría a buscar una carrera llamada «buscar».
     */
    get: operations["buscar_carreras_api_carreras_buscar_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/carreras/{id_carrera}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar una carrera y su fuente
     * @description La ficha institucional de una carrera, con la fuente que la respalda.
     *
     *     **Un identificador que no existe es un 404 y no la carrera más parecida.**
     *     Quien pide una carrera por su id no está buscando: contestarle con otra
     *     sería contestar una pregunta que no hizo, y en una pantalla que muestra
     *     información institucional eso se lee como un dato de la Facultad.
     *
     *     **Una carrera retenida por validación es un 409 y no un 404**, porque no es
     *     lo mismo que no exista. Tampoco un 403: el frontend lee el 403 como
     *     consentimiento pendiente (HU-03a) y reabriría el aviso.
     *
     *     **Sólo la ficha anota `carrera_consultada`** (VOCAIA-60), y sólo si se
     *     devolvió: listar y buscar son el camino hasta la ficha, y un 404 o un 409 no
     *     es una carrera leída.
     */
    get: operations["obtener_carrera_api_carreras__id_carrera__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conversacion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar las sesiones de la persona autenticada
     * @description Devuelve las sesiones de quien consulta, de la más reciente a la más vieja.
     *
     *     El listado no toma ningún parámetro de a quién pertenecen las sesiones: el
     *     identificador sale de la credencial verificada y no de la petición, así que
     *     no hay forma de pedir el historial de otra persona.
     */
    get: operations["listar_sesiones_api_conversacion_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conversacion/{sesion_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar el historial de una sesión
     * @description Devuelve los turnos de la sesión y con qué versiones se ejecutó.
     */
    get: operations["obtener_historial_api_conversacion__sesion_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conversacion/{sesion_id}/mensaje": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enviar un mensaje y recibir la respuesta en streaming
     * @description Responde en streaming y, recién después, extrae evidencia del turno.
     *
     *     Si la sesión no existe, se crea con este mensaje: no hay endpoint de alta.
     *     Queda a nombre de quien la abre, y sólo esa persona puede seguirla.
     */
    post: operations["enviar_mensaje_api_conversacion__sesion_id__mensaje_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conversacion/{sesion_id}/turnos/{turno}/trazabilidad": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ver de dónde salió una respuesta del sistema
     * @description Qué sostiene una respuesta, con lo que contó la persona separado de lo que dice la Facultad.
     *
     *     S3-10 (VOCAIA-115), el lado HTTP de HU-18. Los tres casos en que no hay traza
     *     se contestan con el mismo 404, igual que el historial: a quien prueba con una
     *     sesión ajena no se le confirma que existe.
     */
    get: operations["obtener_trazabilidad_api_conversacion__sesion_id__turnos__turno__trazabilidad_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/identidad/consentimiento": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Registrar el consentimiento informado y crear la identidad
     * @description Deja constancia del consentimiento. Es lo que crea la identidad.
     *
     *     Este es el único endpoint que hace nacer una fila en el vault (HU-03a): el
     *     resto del sistema resuelve identidades que ya existen. Mientras la persona
     *     no pase por acá, el backend no guarda ni su correo ni su nombre, que es lo
     *     que pide la Ley 25.326 y el criterio de aceptación de la historia.
     *
     *     Es idempotente: volver a llamarlo actualiza la versión consentida, que es
     *     lo que corresponde cuando el aviso cambió y la persona lo acepta de nuevo.
     */
    post: operations["consentir_api_identidad_consentimiento_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/identidad/salir": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cerrar la sesión del usuario
     * @description Corta las sesiones vigentes. No da de baja la cuenta.
     *
     *     El token que emitió el proveedor sigue siendo válido para él hasta que
     *     venza —no se lo puede desactivar desde acá—, pero deja de ser aceptado por
     *     VocaIA. El frontend igualmente tiene que descartarlo.
     *
     *     Después de esto la persona vuelve a entrar normalmente: el ingreso le trae
     *     un token nuevo, posterior al corte. Dar de baja la cuenta es otra cosa y
     *     llega con HU-04.
     */
    post: operations["salir_api_identidad_salir_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/identidad/yo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar la identidad del usuario autenticado
     * @description Verifica el token y devuelve el identificador opaco.
     *
     *     Es también el endpoint con el que el frontend comprueba que su token sigue
     *     valiendo, sin tener que iniciar una conversación para averiguarlo.
     */
    get: operations["consultar_identidad_api_identidad_yo_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/perfil": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar mi perfil vocacional y en qué se basa
     * @description Devuelve el perfil de quien consulta, con los fragmentos que lo sostienen.
     *
     *     **Siempre devuelve un perfil, nunca un 404.** Quien todavía no conversó
     *     recibe uno donde ninguna dimensión afirma nada, que es exactamente lo que el
     *     sistema sabe de esa persona. Un error obligaría al cliente a distinguir dos
     *     casos que para quien lo lee son el mismo.
     *
     *     El perfil se devuelve aunque no alcance para recomendar carreras: `publicable`
     *     dice si llegó a ese umbral, y por debajo lo que corresponde es proponer
     *     seguir explorando, no esconder lo que hay.
     */
    get: operations["obtener_perfil_api_perfil_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/perfil/objeciones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Marcar que una inferencia del perfil no me representa
     * @description Registra el desacuerdo de la persona con lo que el perfil dice de una dimensión.
     *
     *     **No corrige el perfil.** El motor va a seguir calculando lo mismo, porque
     *     lo que la persona contó no cambió. Lo que queda asentado es que no se
     *     reconoce en lo que se infirió de eso, y esa discrepancia es un dato que
     *     tacharlo haría desaparecer.
     *
     *     Es idempotente por dimensión: volver a objetar la misma actualiza el motivo
     *     y la fecha en lugar de apilar registros. La objeción se recupera después en
     *     `GET /api/perfil`, dentro del rasgo al que corresponde.
     */
    post: operations["objetar_api_perfil_objeciones_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/salud": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verificar que el servicio responde
     * @description Devuelve el estado del proceso.
     */
    get: operations["consultar_salud_salud_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CarreraSalida
     * @description Una carrera del corpus institucional, con la fuente que la respalda.
     *
     *     Sale del corpus tal como se indexó: no pasa por el modelo, así que el texto
     *     es el mismo en cada llamada y no hay nada que verificar contra una fuente
     *     —la fuente viene pegada—. Es la forma que cumple el primer criterio de
     *     HU-15 por construcción.
     */
    CarreraSalida: {
      /**
       * Denominacion
       * @description Denominación oficial, para mostrar.
       */
      denominacion: string;
      /**
       * Estado
       * @description Situación de la carrera, por ejemplo `activa`.
       */
      estado: string;
      /**
       * Estado Validacion
       * @description `provisional` mientras la Facultad no valide el contenido (R-002). Quien lo muestre tiene que decirlo: no es información oficial confirmada.
       */
      estado_validacion: string;
      /**
       * Fuente
       * @description Denominación de la fuente y su ubicación.
       */
      fuente: string;
      /**
       * Id
       * @description Slug estable de la carrera en el corpus.
       */
      id: string;
      /**
       * Nivel
       * @description `grado`, `tecnicatura` o `pregrado`.
       */
      nivel: string;
      /**
       * Texto
       * @description La descripción institucional completa.
       */
      texto: string;
    };
    /**
     * CoincidenciaCarreraSalida
     * @description Una carrera encontrada por parecido, con cuánto se parece.
     */
    CoincidenciaCarreraSalida: {
      carrera: components["schemas"]["CarreraSalida"];
      /**
       * Puntaje
       * @description Creciente en similitud, 1.0 = idéntico. **No está acotado a [0, 1]**: el índice devuelve `1 - distancia_coseno`, que va de 1 a -1. Sirve para ordenar, no como porcentaje de acierto.
       */
      puntaje: number;
    };
    /**
     * ConsentimientoEntrada
     * @description Versión del aviso que la persona aceptó.
     *
     *     Se pide la versión y no un booleano: el aviso va a cambiar, y un `true`
     *     suelto no dice qué fue lo que se aceptó. Sin eso el registro no sirve como
     *     prueba de consentimiento informado.
     */
    ConsentimientoEntrada: {
      /**
       * Version
       * @description Identificador de la versión del aviso aceptada.
       */
      version: string;
    };
    /**
     * EstadoServicio
     * @description Respuesta de `/salud`.
     */
    EstadoServicio: {
      /** Entorno */
      entorno: string;
      /** Estado */
      estado: string;
      /** Version */
      version: string;
    };
    /**
     * EvidenciaSalida
     * @description Un fragmento textual que sostiene un rasgo.
     *
     *     Es la respuesta a «en qué se basa esto» (RNF-05). El fragmento es literal:
     *     sale tal cual de algo que la persona escribió, y por eso puede leerlo y
     *     decir que no la representa.
     */
    EvidenciaSalida: {
      /**
       * Confianza
       * @description Cómo declaró el extractor esta lectura.
       */
      confianza: string;
      /**
       * Confianza Degradada
       * @description La lectura quedó en duda por un marcador de influencia externa. No se descarta: pesa menos.
       */
      confianza_degradada: boolean;
      /**
       * Emitida En
       * Format: date-time
       */
      emitida_en: string;
      /**
       * Fragmento
       * @description Cita literal de lo que la persona escribió.
       */
      fragmento: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Sesion Id
       * Format: uuid
       */
      sesion_id: string;
      /** Turno */
      turno: number;
      /**
       * Valencia
       * @description De -2 (rechazo) a 2 (interés fuerte).
       */
      valencia: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HistorialSalida
     * @description Estado completo de una sesión.
     *
     *     Incluye las versiones de artefactos con las que se ejecutó: sin eso, el
     *     historial no se puede interpretar más adelante.
     */
    HistorialSalida: {
      /**
       * Actualizada En
       * Format: date-time
       */
      actualizada_en: string;
      /** Estado */
      estado: string;
      /**
       * Iniciada En
       * Format: date-time
       */
      iniciada_en: string;
      /**
       * Sesion Id
       * Format: uuid
       */
      sesion_id: string;
      /** Turnos */
      turnos: components["schemas"]["TurnoSalida"][];
      /** Version Instrumento */
      version_instrumento: string;
      /** Version Prompt */
      version_prompt: string;
    };
    /**
     * MensajeEntrada
     * @description Lo que manda el usuario.
     */
    MensajeEntrada: {
      /**
       * Contenido
       * @description Texto del mensaje. No puede estar vacío.
       */
      contenido: string;
    };
    /**
     * ObjecionEntrada
     * @description Lo que manda quien dice que una inferencia no lo representa.
     */
    ObjecionEntrada: {
      /**
       * Dimension
       * @description Código de la dimensión del perfil que se objeta.
       */
      dimension: string;
      /**
       * Motivo
       * @description Por qué no representa a la persona. Opcional: exigirlo convertiría en trámite algo que tiene que costar un clic, y una objeción sin explicación sigue siendo una objeción.
       * @default
       */
      motivo: string;
    };
    /**
     * ObjecionSalida
     * @description Una objeción registrada.
     *
     *     No lleva identificador propio: para quien la lee es «esta dimensión, que
     *     dije que no me representa», y la dimensión ya la identifica —hay una sola
     *     objeción vigente por dimensión—.
     */
    ObjecionSalida: {
      /** Dimension */
      dimension: string;
      /** Motivo */
      motivo: string;
      /**
       * Registrada En
       * Format: date-time
       */
      registrada_en: string;
      /**
       * Version Instrumento
       * @description Con qué versión de reglas estaba armado el perfil que la persona vio al objetar. La objeción es sobre lo que vio, no sobre lo que se calcule después.
       */
      version_instrumento: string;
    };
    /**
     * PerfilSalida
     * @description El perfil completo de una persona.
     *
     *     Incluye las dimensiones sin evidencia, con `confianza: insuficiente`. Quien
     *     lo muestre tiene que poder decir «de esto todavía no hablamos», que no es lo
     *     mismo que un cero.
     */
    PerfilSalida: {
      /** Actualizado En */
      actualizado_en: string | null;
      /**
       * Publicable
       * @description Si el perfil alcanza para recomendar carreras. Por debajo del umbral se muestra igual y lo que corresponde es proponer seguir explorando.
       */
      publicable: boolean;
      /** Rasgos */
      rasgos: components["schemas"]["RasgoSalida"][];
      /**
       * Sesiones
       * @description Las sesiones cuya evidencia entró en el cálculo.
       */
      sesiones: string[];
      /**
       * Version Instrumento
       * @description Con qué versión de reglas se construyó. Dos perfiles con versiones distintas no son comparables.
       */
      version_instrumento: string;
    };
    /**
     * RasgoSalida
     * @description Una dimensión del perfil, con nombre legible y su respaldo.
     */
    RasgoSalida: {
      /**
       * Confianza
       * @description `insuficiente`, `baja`, `media` o `alta`. `insuficiente` no es un valor bajo: es que la persona no habló de esto y el sistema no infiere nada.
       */
      confianza: string;
      /** Descripcion */
      descripcion: string;
      /**
       * Dimension
       * @description Código de la dimensión en el instrumento.
       */
      dimension: string;
      /** Evidencias */
      evidencias: components["schemas"]["EvidenciaSalida"][];
      /**
       * Intensidad
       * @description De -2 a 2, en la misma escala que la valencia.
       */
      intensidad: number;
      /** Nombre */
      nombre: string;
      /** @description La persona declaró que esto no la representa. El rasgo se devuelve igual y con los mismos números: lo que la objeción registra es el desacuerdo, no una corrección. Quien muestre el perfil tiene que mostrar las dos cosas. */
      objecion?: components["schemas"]["ObjecionSalida"] | null;
      /** Soporte */
      soporte: number;
      /** Unidades */
      unidades: number;
    };
    /**
     * RespaldoConversacionalSalida
     * @description Algo que la persona contó, que el sistema tenía leído al responder.
     *
     *     **Disponible, no necesariamente usado**: es el mismo matiz que «consultada y
     *     no citada» del lado del corpus. Quien lo muestre tiene que rotularlo como lo
     *     que el sistema sabía de la persona, no como aquello en lo que se basó.
     */
    RespaldoConversacionalSalida: {
      /**
       * Confianza
       * @description Cómo declaró el extractor esta lectura.
       */
      confianza: string;
      /**
       * Confianza Degradada
       * @description La lectura quedó en duda por un marcador de influencia externa. No se descarta: pesa menos.
       */
      confianza_degradada: boolean;
      /**
       * Dimension
       * @description Código de la dimensión del instrumento que lee.
       */
      dimension: string;
      /**
       * Emitida En
       * Format: date-time
       */
      emitida_en: string;
      /**
       * Fragmento
       * @description Cita literal de lo que la persona escribió.
       */
      fragmento: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Procedencia
       * @description Siempre `conversacion`: lo contó la persona, no lo dice la Facultad.
       * @constant
       */
      procedencia: "conversacion";
      /**
       * Sesion Id
       * Format: uuid
       */
      sesion_id: string;
      /** Turno */
      turno: number;
      /**
       * Valencia
       * @description De -2 (rechazo) a 2 (interés fuerte).
       */
      valencia: number;
    };
    /**
     * RespaldoInstitucionalSalida
     * @description Un fragmento del corpus que acompañó a la respuesta, tal como estaba al darla.
     */
    RespaldoInstitucionalSalida: {
      /**
       * Citado
       * @description Si la respuesta lo citó con su `[n]`. Consultado no es lo mismo que citado.
       */
      citado: boolean;
      /**
       * Estado Validacion
       * @description El que tenía el fragmento **cuando se dio la respuesta**, no el de hoy. `provisional` mientras la Facultad no valide el contenido.
       */
      estado_validacion: string;
      /**
       * Fuente
       * @description Denominación de la fuente institucional y su ubicación.
       */
      fuente: string;
      /**
       * Id
       * @description Slug del fragmento en el corpus.
       */
      id: string;
      /**
       * Orden
       * @description El `[n]` con el que se le presentó al modelo.
       */
      orden: number;
      /**
       * Procedencia
       * @description Siempre `corpus`: lo dice la Facultad, no lo contó la persona.
       * @constant
       */
      procedencia: "corpus";
      /**
       * Puntaje
       * @description Creciente en similitud, 1.0 = idéntico. **No está acotado a [0, 1]**: sirve para ordenar, no como porcentaje de acierto.
       */
      puntaje: number;
    };
    /**
     * ResumenSesionSalida
     * @description Una sesión en el listado del historial, sin sus turnos.
     */
    ResumenSesionSalida: {
      /**
       * Actualizada En
       * Format: date-time
       */
      actualizada_en: string;
      /**
       * Cantidad Turnos
       * @description Turnos persistidos, de la persona y del agente.
       */
      cantidad_turnos: number;
      /**
       * Estado
       * @description `abierta`, `cerrada` o `derivada`.
       */
      estado: string;
      /**
       * Iniciada En
       * Format: date-time
       */
      iniciada_en: string;
      /**
       * Sesion Id
       * Format: uuid
       */
      sesion_id: string;
      /**
       * Vista Previa
       * @description Primer mensaje de la persona en esa sesión, para poder reconocerla en la lista. Es `null` si la sesión sólo tiene el mensaje de encuadre del agente.
       */
      vista_previa?: string | null;
    };
    /**
     * TrazabilidadSalida
     * @description De dónde salió una respuesta del sistema, separado por procedencia (HU-18).
     *
     *     Las dos listas van separadas y cada pieza trae además su `procedencia`: una
     *     pantalla que las junte en una sola lista sigue pudiendo distinguirlas, y
     *     ninguna puede leer una inferencia sobre la persona con la autoridad de una
     *     ordenanza.
     */
    TrazabilidadSalida: {
      /** Conversacional */
      conversacional: components["schemas"]["RespaldoConversacionalSalida"][];
      /**
       * Evidencia Leida Hasta
       * @description Hasta cuándo llega la evidencia que el sistema pudo tener al responder: el mensaje que la respuesta contesta. `null` en el encuadre, que no contesta nada.
       */
      evidencia_leida_hasta: string | null;
      /** Institucional */
      institucional: components["schemas"]["RespaldoInstitucionalSalida"][];
      /**
       * Respondida En
       * Format: date-time
       */
      respondida_en: string;
      /**
       * Sesion Id
       * Format: uuid
       */
      sesion_id: string;
      /**
       * Sin Respaldo
       * @description Ni evidencia ni corpus. El encuadre sale siempre así, porque es texto fijo: no conviene mostrarlo como una afirmación sin respaldo.
       */
      sin_respaldo: boolean;
      /**
       * Turno
       * @description El turno del agente cuya procedencia se describe.
       */
      turno: number;
    };
    /**
     * TurnoSalida
     * @description Una intervención del historial.
     */
    TurnoSalida: {
      /** Contenido */
      contenido: string;
      /** Numero */
      numero: number;
      /**
       * Ocurrido En
       * Format: date-time
       */
      ocurrido_en: string;
      /**
       * Rol
       * @description `usuario` o `agente`.
       */
      rol: string;
    };
    /**
     * UsuarioSalida
     * @description Lo único que la API dice sobre quién sos.
     *
     *     **No incluye nombre ni correo**, y no es una omisión a completar después:
     *     esos datos viven en el esquema `vault` y no cruzan hacia el resto del
     *     sistema. Un endpoint que los devolviera convertiría la separación en
     *     decorativa.
     */
    UsuarioSalida: {
      /**
       * Identificador Opaco
       * @description Identificador estable del usuario. No revela nada sobre la persona.
       */
      identificador_opaco: string;
      /**
       * Proveedor
       * @description Proveedor de identidad que emitió el token.
       */
      proveedor: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listar_carreras_api_carreras_get: {
    parameters: {
      query?: {
        /** @description Recorta a un nivel: `grado`, `tecnicatura` o `pregrado`. */
        nivel?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CarreraSalida"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  buscar_carreras_api_carreras_buscar_get: {
    parameters: {
      query: {
        /** @description Lo que la persona busca, con sus palabras. */
        texto: string;
        /** @description Recorta a un nivel: `grado`, `tecnicatura` o `pregrado`. */
        nivel?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoincidenciaCarreraSalida"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  obtener_carrera_api_carreras__id_carrera__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id_carrera: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CarreraSalida"];
        };
      };
      /** @description No hay ninguna carrera con ese identificador. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description La carrera existe, pero su contenido todavía no está validado por la Facultad y el filtro de validación está en modo estricto. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  listar_sesiones_api_conversacion_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResumenSesionSalida"][];
        };
      };
    };
  };
  obtener_historial_api_conversacion__sesion_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sesion_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HistorialSalida"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  enviar_mensaje_api_conversacion__sesion_id__mensaje_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sesion_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MensajeEntrada"];
      };
    };
    responses: {
      /** @description Flujo de eventos SSE. Cada evento es una línea `data:` con un objeto JSON: `{'delta': '...'}` por cada trozo de la respuesta, `{'fin': true, 'turno_usuario': N, 'turno_agente': N, 'fuentes': [{'id': '...', 'fuente': '...', 'estado_validacion': '...'}], 'fuentes_retenidas': N}` al cerrar —donde `fuentes` son los fragmentos del corpus que se consultaron para el turno, no necesariamente los que la respuesta cita, y `fuentes_retenidas` los que el filtro de validación dejó afuera, siempre 0 en modo abierto—, y `{'error': '...'}` si la generación se corta. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
          "text/event-stream": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description La sesión alcanzó el techo de turnos de la ventana de 24 horas. No es un error: la conversación puede retomarse más tarde. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  obtener_trazabilidad_api_conversacion__sesion_id__turnos__turno__trazabilidad_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sesion_id: string;
        turno: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrazabilidadSalida"];
        };
      };
      /** @description No hay una respuesta del sistema con ese número en una sesión de esta persona: la sesión no existe, es de otra persona, o el turno es un mensaje de la persona. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  consentir_api_identidad_consentimiento_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentimientoEntrada"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsuarioSalida"];
        };
      };
      /** @description Credencial ausente, vencida o inválida. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  salir_api_identidad_salir_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Credencial ausente, vencida o inválida. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  consultar_identidad_api_identidad_yo_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsuarioSalida"];
        };
      };
      /** @description Credencial ausente, vencida o inválida. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Falta registrar el consentimiento informado. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  obtener_perfil_api_perfil_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PerfilSalida"];
        };
      };
    };
  };
  objetar_api_perfil_objeciones_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ObjecionEntrada"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ObjecionSalida"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  consultar_salud_salud_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EstadoServicio"];
        };
      };
    };
  };
}
