/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/conversacion/{sesion_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar el historial de una sesión
     * @description Devuelve los turnos de la sesión y con qué versiones se ejecutó.
     */
    get: operations["obtener_historial_api_conversacion__sesion_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conversacion/{sesion_id}/mensaje": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enviar un mensaje y recibir la respuesta en streaming
     * @description Responde en streaming y, recién después, extrae evidencia del turno.
     *
     *     Si la sesión no existe, se crea con este mensaje: no hay endpoint de alta.
     */
    post: operations["enviar_mensaje_api_conversacion__sesion_id__mensaje_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/identidad/consentimiento": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Registrar el consentimiento informado y crear la identidad
     * @description Deja constancia del consentimiento. Es lo que crea la identidad.
     *
     *     Este es el único endpoint que hace nacer una fila en el vault (HU-03a): el
     *     resto del sistema resuelve identidades que ya existen. Mientras la persona
     *     no pase por acá, el backend no guarda ni su correo ni su nombre, que es lo
     *     que pide la Ley 25.326 y el criterio de aceptación de la historia.
     *
     *     Es idempotente: volver a llamarlo actualiza la versión consentida, que es
     *     lo que corresponde cuando el aviso cambió y la persona lo acepta de nuevo.
     */
    post: operations["consentir_api_identidad_consentimiento_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/identidad/salir": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cerrar la sesión del usuario
     * @description Corta las sesiones vigentes. No da de baja la cuenta.
     *
     *     El token que emitió el proveedor sigue siendo válido para él hasta que
     *     venza —no se lo puede desactivar desde acá—, pero deja de ser aceptado por
     *     VocaIA. El frontend igualmente tiene que descartarlo.
     *
     *     Después de esto la persona vuelve a entrar normalmente: el ingreso le trae
     *     un token nuevo, posterior al corte. Dar de baja la cuenta es otra cosa y
     *     llega con HU-04.
     */
    post: operations["salir_api_identidad_salir_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/identidad/yo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar la identidad del usuario autenticado
     * @description Verifica el token y devuelve el identificador opaco.
     *
     *     Es también el endpoint con el que el frontend comprueba que su token sigue
     *     valiendo, sin tener que iniciar una conversación para averiguarlo.
     */
    get: operations["consultar_identidad_api_identidad_yo_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/salud": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verificar que el servicio responde
     * @description Devuelve el estado del proceso.
     */
    get: operations["consultar_salud_salud_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ConsentimientoEntrada
     * @description Versión del aviso que la persona aceptó.
     *
     *     Se pide la versión y no un booleano: el aviso va a cambiar, y un `true`
     *     suelto no dice qué fue lo que se aceptó. Sin eso el registro no sirve como
     *     prueba de consentimiento informado.
     */
    ConsentimientoEntrada: {
      /**
       * Version
       * @description Identificador de la versión del aviso aceptada.
       */
      version: string;
    };
    /**
     * EstadoServicio
     * @description Respuesta de `/salud`.
     */
    EstadoServicio: {
      /** Entorno */
      entorno: string;
      /** Estado */
      estado: string;
      /** Version */
      version: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HistorialSalida
     * @description Estado completo de una sesión.
     *
     *     Incluye las versiones de artefactos con las que se ejecutó: sin eso, el
     *     historial no se puede interpretar más adelante.
     */
    HistorialSalida: {
      /**
       * Actualizada En
       * Format: date-time
       */
      actualizada_en: string;
      /** Estado */
      estado: string;
      /**
       * Iniciada En
       * Format: date-time
       */
      iniciada_en: string;
      /**
       * Sesion Id
       * Format: uuid
       */
      sesion_id: string;
      /** Turnos */
      turnos: components["schemas"]["TurnoSalida"][];
      /** Version Instrumento */
      version_instrumento: string;
      /** Version Prompt */
      version_prompt: string;
    };
    /**
     * MensajeEntrada
     * @description Lo que manda el usuario.
     */
    MensajeEntrada: {
      /**
       * Contenido
       * @description Texto del mensaje. No puede estar vacío.
       */
      contenido: string;
    };
    /**
     * TurnoSalida
     * @description Una intervención del historial.
     */
    TurnoSalida: {
      /** Contenido */
      contenido: string;
      /** Numero */
      numero: number;
      /**
       * Ocurrido En
       * Format: date-time
       */
      ocurrido_en: string;
      /**
       * Rol
       * @description `usuario` o `agente`.
       */
      rol: string;
    };
    /**
     * UsuarioSalida
     * @description Lo único que la API dice sobre quién sos.
     *
     *     **No incluye nombre ni correo**, y no es una omisión a completar después:
     *     esos datos viven en el esquema `vault` y no cruzan hacia el resto del
     *     sistema. Un endpoint que los devolviera convertiría la separación en
     *     decorativa.
     */
    UsuarioSalida: {
      /**
       * Identificador Opaco
       * @description Identificador estable del usuario. No revela nada sobre la persona.
       */
      identificador_opaco: string;
      /**
       * Proveedor
       * @description Proveedor de identidad que emitió el token.
       */
      proveedor: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  obtener_historial_api_conversacion__sesion_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sesion_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HistorialSalida"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  enviar_mensaje_api_conversacion__sesion_id__mensaje_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sesion_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MensajeEntrada"];
      };
    };
    responses: {
      /** @description Flujo de eventos SSE. Cada evento es una línea `data:` con un objeto JSON: `{'delta': '...'}` por cada trozo de la respuesta, `{'fin': true, 'turno_usuario': N, 'turno_agente': N}` al cerrar, y `{'error': '...'}` si la generación se corta. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
          "text/event-stream": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  consentir_api_identidad_consentimiento_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentimientoEntrada"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsuarioSalida"];
        };
      };
      /** @description Credencial ausente, vencida o inválida. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  salir_api_identidad_salir_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Credencial ausente, vencida o inválida. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  consultar_identidad_api_identidad_yo_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsuarioSalida"];
        };
      };
      /** @description Credencial ausente, vencida o inválida. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Falta registrar el consentimiento informado. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  consultar_salud_salud_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EstadoServicio"];
        };
      };
    };
  };
}
